// Copyright Yooshley. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace BequestGameplayTags
{
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Move);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Charge);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Deflect);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Guard);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Evade);
	
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Guard_Left);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Guard_Right);
	
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip);

	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Equipment_Sword_2H);

	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Hurt);
	
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Hit);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Hurt);
	
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Hurt_Front);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Hurt_Back);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Hurt_Left);
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Hurt_Right);
	
	BEQUEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_Damage);
}
